FROM node:latest

WORKDIR /app/client

COPY package*.json ./

ENV PATH /app/client/node_modules/.bin:$PATH

RUN npm install

RUN npm install react-scripts -g

COPY ./ ./

CMD ["npm", "run", "start"]

